require 'exifice/objects/lat_lon'
require 'exifice/objects/point'
require 'exifice/objects/point_3d'
require 'exifice/objects/point_4d'
require 'exifice/objects/point_5d'
require 'exifice/objects/photo'
require 'exifice/objects/track'
